version: "3"

services:
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
                WWWUSER: 1000
                WWWGROUP: 1000
        volumes:
            - ../:/var/www/symfony:cached
            - scarping_app_var:/var/www/symfony/var
            - scarping_app_vendor:/var/www/symfony/vendor
        networks:
            - scarping_app
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony:cached
            - scarping_app_var:/var/www/symfony/var
            - scarping_app_vendor:/var/www/symfony/vendor
        ports:
            - 80:80
        networks:
            - scarping_app
        env_file:
            - .env.nginx.local
    db:
        image: mysql:8.0.33
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - scarping_app
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        restart: always
        ports:
            - "90:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
        networks:
            - scarping_app
    rabbitmq:
        build:
            context: ./rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - scarping_app
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - scarping_app
volumes:
    scarping_app_var:
    scarping_app_vendor:
    db_app:

networks:
    scarping_app: